In [1]:
!pip3 install numpy

Working with numpy functions

In [10]:
import numpy as np

In [3]:
arr=np.array([[1,2,3],[4,5,6]])     #in numpy arrays are n-dimensionals

In [4]:
type(arr)       #this is numpy array

numpy.ndarray

In [5]:
arr.ndim

2

In [6]:
arr.shape           #(no of rows,no of columns)

(2, 3)

In [7]:
a1=np.array([1,2,3])

In [10]:
a1.ndim

1

In [11]:
a1.shape   #(3,)  1-d array 

(3,)

In [13]:
arr.size       #no of elements

6

In [14]:
a1.size          

3

In [15]:
arr.dtype

dtype('int32')

In [16]:
a2=np.array(["hello",1,"st","time"])

In [17]:
a2.dtype

dtype('<U5')

# 4ways to create numpy array

In [18]:
#creating array from list with type float
a=np.array([[1,2,4],[5,6,7]], dtype='float')
print("Array created using passed list \n",a)

Array created using passed list 
 [[1. 2. 4.]
 [5. 6. 7.]]


In [19]:
#creating array from tuple
b=np.array((1,2,4))
print("Array created using passed tuples \n",b)

Array created using passed tuples 
 [1 2 4]


In [20]:
#creating array from tuple with type float
b1=np.array(((1,2,4),(5,6,7)), dtype='float')
print("Array created using passed tuple \n",b1)

Array created using passed tuple 
 [[1. 2. 4.]
 [5. 6. 7.]]


In [21]:
c=np.zeros((3,4))          #null matrix

In [22]:
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
c1=np.ones((3,4))         # initialize with one
c1               

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
c2=np.eye(3)          #c2 create identity matrix diagonal 1 ,rest 0

In [25]:
c2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
np.arange ?   #to see documentation np.<fun_name>? then press shift+enter
#arange return evenly spaced value within the interval

SyntaxError: invalid syntax (<ipython-input-29-41b50f10c70f>, line 1)

In [34]:
np.arange?   #do not anything in comment toooooo

SyntaxError: invalid syntax (<ipython-input-34-66df84668321>, line 1)

In [36]:
np.arange?

In [37]:
np.arange(0,30,5)         # here 5 is step size

array([ 0,  5, 10, 15, 20, 25])

In [38]:
np.linspace(0,20,3)  # here 3 is number of values we want and they are equally spaced

array([ 0., 10., 20.])

In [41]:
e=np.random.random((3,3))
print("random values: ",e)

random values:  [[0.24709648 0.60202398 0.99373327]
 [0.63662597 0.47292872 0.18487681]
 [0.24461273 0.51280876 0.60302618]]


In [42]:
#reshape is very important function it will change the dimension
arr=np.array([[1,2,3,4],
             [5,6,7,8],
             [9,2,1,6]])
newarr=arr.reshape(2,2,3)
newarr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [2, 1, 6]]])

In [43]:
arr=np.array([[1,2,3,4],
             [5,6,7,8],
             [9,2,1,6]])
newarr=arr.reshape(4,3)
newarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [2, 1, 6]])

In [45]:
arr=np.array([[1,2,3,4],
             [5,6,7,8],
             [9,2,1,6]])
print("Flatten array is :",arr.flatten())

Flatten array is : [1 2 3 4 5 6 7 8 9 2 1 6]


# array indexing

In [46]:
arr=np.array([[1,2,3,4],
             [5,6,7,8],
             [9,2,1,6]])
arr[1:,:3]      #see info from copy indexing in numpy

array([[5, 6, 7],
       [9, 2, 1]])

In [47]:
arr=np.array([[1,2.5,3,4],
             [5,6,7,8],
             [9.4,2,1,6]])
arr[1:,:3] 

array([[5. , 6. , 7. ],
       [9.4, 2. , 1. ]])

In [9]:
arr=np.array([[1,2.5,3,4],
             [5,6,-7,8],
             [9.4,2,1,6]])
arr[1:,:3:2] 

array([[ 5. , -7. ],
       [ 9.4,  1. ]])

In [10]:
cond=arr>0    #known as conditional indexing
temp=arr[cond]     
print("\n Elements greater than 0 : \n",temp)
print(cond)        #boolean array according to the condition 


 Elements greater than 0 : 
 [1.  2.5 3.  4.  5.  6.  8.  9.4 2.  1.  6. ]
[[ True  True  True  True]
 [ True  True False  True]
 [ True  True  True  True]]


# Basic operations
### we can use overloaded aritnmetic operators

### also known as broadcating feature as it is replicating in whole array

In [14]:
arr=np.array([1,2,3,4])
#adding 1 to all
arr+=1
print(arr)
# sub 3 to all
arr-=3
print(arr)
# multiply to 4 to all
arr*=4
print(arr)
# square of all
print(arr**2)

[2 3 4 5]
[-1  0  1  2]
[-4  0  4  8]
[16  0 16 64]


## Transpose of a array

In [15]:
a1=np.array([[12,3,4,5],[6,7,8,9],[2,34,45,6]])
print("Original array\n",a1)
print("Transpose of array is\n",a1.T)

Original array
 [[12  3  4  5]
 [ 6  7  8  9]
 [ 2 34 45  6]]
Transpose of array is
 [[12  6  2]
 [ 3  7 34]
 [ 4  8 45]
 [ 5  9  6]]


In [22]:
print("maximum element of array :",a1.max())
print("Column wise minimum elements ",a1.min(axis=0))
print("Row wise minimum elements ",a1.min(axis=1))
print("Sum of all elements of array : ",a1.sum())
print("Cumulative sum along each row :",a1.cumsum(axis=0))

maximum element of array : 45
Column wise minimum elements  [2 3 4 5]
Row wise minimum elements  [3 6 2]
Sum of all elements of array :  141
Cumulative sum along each row : [[12  3  4  5]
 [18 10 12 14]
 [20 44 57 20]]


# Binary operators and matrix

In [27]:
a=np.array([[1,3,4],[2,5,7],[3,7,4]])
b=np.array([[2,5,3],[7,5,3],[2,7,4]])
print("Array sum\n ",a+b)
print("Array *element wise* multiplication :\n ",a*b)
print("Matrix multiplication :\n",a.dot(b))

Array sum
  [[ 3  8  7]
 [ 9 10 10]
 [ 5 14  8]]
Array *element wise* multiplication :
  [[ 2 15 12]
 [14 25 21]
 [ 6 49 16]]
Matrix multiplication :
 [[31 48 28]
 [53 84 49]
 [63 78 46]]


# Universal Functions : np.functionname(array)
### sin, cos, exp

In [32]:
print(np.pi)
a=np.array([0,np.pi/2,np.pi])
print("Sine value of all : ",np.sin(a))
print("Cosine value of all : ",np.cos(a))
print("Tangent value of all : ",np.tan(a))
#   error -> print("Cosec value of all : ",np.cosec(a))
print("Exponent value of all ",np.exp(a))
print("Square root of all ",np.sqrt(a))

3.141592653589793
Sine value of all :  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Cosine value of all :  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
Tangent value of all :  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]
Exponent value of all  [ 1.          4.81047738 23.14069263]
Square root of all  [0.         1.25331414 1.77245385]


# Sorting Array
### np.sort( array , axis=0/1 ,kind= 'mergesort'/'quicksort'/...)

In [46]:
a=np.array([[2,6,3],[54,76,2],[3,8,0]])
print("Element in sorted order is :\n",np.sort(a))        #get row wise sorted bydefault axis=1
print("All element in sorted order  in one line is :\n",np.sort(a, axis=None ,kind='quicksort'))
print("All element in sorted order  in one line is :\n",np.sort(a, axis=None ,kind='mergesort'))
print("All element in sorted order  in one line is :\n",np.sort(a, axis=None ,kind='heapsort'))
# error-> print("All element in sorted order  in one line is :\n",np.sort(a, axis=None ,kind='bubblesort'))
print("Row wise sorted order is :\n",np.sort(a, axis=1))
print("Column wise sorted order is :\n",np.sort(a, axis=0))

Element in sorted order is :
 [[ 2  3  6]
 [ 2 54 76]
 [ 0  3  8]]
All element in sorted order  in one line is :
 [ 0  2  2  3  3  6  8 54 76]
All element in sorted order  in one line is :
 [ 0  2  2  3  3  6  8 54 76]
All element in sorted order  in one line is :
 [ 0  2  2  3  3  6  8 54 76]
Row wise sorted order is :
 [[ 2  3  6]
 [ 2 54 76]
 [ 0  3  8]]
Column wise sorted order is :
 [[ 2  6  0]
 [ 3  8  2]
 [54 76  3]]


# sorting of structured array
## np.sort(array, order= 'on the basis of','on the basis of')

In [7]:
# seting alias name for dtype
dtypes=[('name','S10'),('grad_year',int),('cgpa',float)]
#values to be put in array
values=[('Apoorva',2021,8.90),('Anushka',2021,8.7),('Aarohika',2022,8),('Avint',2022,7)]
#creating array
arr=np.array(values,dtype=dtypes)
print(np.sort(arr))
print("Array sorted by names :\n",np.sort(arr, order='name'))
print("Array sorted by graduation year and then cgpa : \n",np.sort(arr,order=['grad_year','cgpa']))

[(b'A', 2021, 8.7) (b'A', 2021, 8.9) (b'A', 2022, 7. ) (b'A', 2022, 8. )]
Array sorted by names :
 [(b'A', 2021, 8.7) (b'A', 2021, 8.9) (b'A', 2022, 7. ) (b'A', 2022, 8. )]
Array sorted by graduation year and then cgpa : 
 [(b'A', 2021, 8.7) (b'A', 2021, 8.9) (b'A', 2022, 7. ) (b'A', 2022, 8. )]


# Stacking and Splitting

## several arrays can be stacked together along different axes.

### *np.vstack((a,b)) : To stack arrays along vertical axis.
### *np.hstack : To stack arrays along horizontal axis.
### *np.column_stack : To stack 1-D arrays as columns into 2-D arrays.
### *np.concatenate : To stack arrays along specified axis(axis is passed as argument).

In [13]:
a=np.array([[2,3],[4,5]])
b=np.array([[8,2],[5,1]])
print("Vertical Stacking :\n",np.vstack((a,b)))
print("Horizontal Stacking :\n",np.hstack((a,b)))
c=[9,8]
print("Column Stacking :\n",np.column_stack((a,c)))
print("concatenating to 2nd axis :",np.concatenate((a,b),1))
print("concatenating to 1nd axis :",np.concatenate((a,b),0))

Vertical Stacking :
 [[2 3]
 [4 5]
 [8 2]
 [5 1]]
Horizontal Stacking :
 [[2 3 8 2]
 [4 5 5 1]]
Column Stacking :
 [[2 3 9]
 [4 5 8]]
concatenating to 2nd axis : [[2 3 8 2]
 [4 5 5 1]]
concatenating to 1nd axis : [[2 3]
 [4 5]
 [8 2]
 [5 1]]


# Splitting functions
##  **np.hsplit - split array along horizontal axis
##  **np.vsplit - split array along vertical axis
##  **np.array_split - split array along specified axis

In [25]:
a=np.array([[1,3,5,6,7,8],[91,32,5,2,6,9]])
print("Splitting along horizontal axis into 2parts : \n",np.hsplit(a,2))
print("Splitting along vertical axis into 2parts : \n",np.vsplit(a,2))
print("Splitting along specified axis into 2parts : \n",np.array_split(a,2,axis=0))

Splitting along horizontal axis into 2parts : 
 [array([[ 1,  3,  5],
       [91, 32,  5]]), array([[6, 7, 8],
       [2, 6, 9]])]
Splitting along vertical axis into 2parts : 
 [array([[1, 3, 5, 6, 7, 8]]), array([[91, 32,  5,  2,  6,  9]])]
Splitting along specified axis into 2parts : 
 [array([[1, 3, 5, 6, 7, 8]]), array([[91, 32,  5,  2,  6,  9]])]


# Statics numpy functions
**min,max

**mean

**median

**average

**variance

**standard deviation

In [29]:
a=np.array([[1,3,5,6,7,8],[91,32,5,2,6,9]])
print("Minimum ",np.min(a))
print("Minimum elements in all column ",np.min(a,axis=1))
print("Minimum elements in all row ",np.min(a,axis=0))

#mean
print("\nMean ",np.mean(a))
print("Mean elements in all column ",np.mean(a,axis=1))
print("Mean elements in all row ",np.mean(a,axis=0))

Minimum  1
Minimum elements in all column  [1 2]
Minimum elements in all row  [1 3 5 2 6 8]

Mean  14.583333333333334
Mean elements in all column  [ 5.         24.16666667]
Mean elements in all row  [46.  17.5  5.   4.   6.5  8.5]


In [5]:
arr=np.array([1,2,4,8,3])

#Mean ,Median
print("Median is :",np.median(arr))
print("Mean is :",np.mean(arr))

#Weighted mean=(n1*w1+n2*w2)/(n1+n2)
#weights
w=np.array([1,1,2,0,1])
print("Weighted mean is :",np.average(arr,weights=w))

#Standard Deviation
u=np.mean(arr)
std_dev=np.sqrt(np.mean(abs(arr-u)**2))
print("Standard deviation is :",std_dev)

#Inbuilt Function for standard deviation is : std
dev=np.std(arr)
print("Standard deviation is :",dev)

# Variance
var=std_dev**2
print("Variance is : ",var)

Median is : 3.0
Mean is : 3.6
Weighted mean is : 2.8
Standard deviation is : 2.4166091947189146
Standard deviation is : 2.4166091947189146
Variance is :  5.840000000000001


# Numpy Random Module
### rand: random values in  given shape
### randn: return a sample(or samples) from the "standard normal" distribution
### randint: return random integer from low(inclusive) to high(exclusive)
### random: return random floats in half interval(0.0,1.0)
### choice: generate a random sample arrary from a given 1-D array
### Shuffle : shuffles the contents of a sequence

In [15]:
a=np.arange(10)+5
print("Array is :",a)
np.random.seed(a)
np.random.shuffle(a)
print("Shuffled array is :",a)
print("Sandard Normal distribution is :",np.random.randn(2,3))
print("4 random integer numbers from 2 to 17 :",np.random.randint(2,17,4))
print("@ random float values are :",np.random.random(2))
print("Pick any random element from array :",np.random.choice([2,5,3,1,7,8]))

Array is : [ 5  6  7  8  9 10 11 12 13 14]
Shuffled array is : [13  5 10 14  7  8 12  6  9 11]
Sandard Normal distribution is : [[-0.20592494 -0.90642348  2.89306998]
 [ 0.752149    1.46752868  0.55966275]]
4 random integer numbers from 2 to 17 : [ 9 13 10  3]
@ random float values are : [0.05022883 0.61622893]
Pick any random element from array : 3
